SET NOCOUNT ON;
BEGIN TRAN;
INSERT INTO Stock (
  DocumentID, DocNumber, Status, AccountKey, AccountName, Address, City, Phone, Batch, TerminalDoc, ValueDate, DueDate, PayDate, Copies, TransType, VatFreeTransType, DiscountPrc, TFtal, VatPrc, TFtalVatFree, TFtalVat, Reference, Remarks, PrintStyle, OriginalPrinted, Details, StockBatch, Warehouse, Agent, TaxType, EvalCurrency, Currency, FatherPriceList, SonPriceList, TransStore, TransAgent, ProtocolID, ExportAddr, UseFID, BranchID, Rate, MainRate, DiscountPrcR, IssueDate, Quantity, Ref3, CostCode, CheqAccKey, CheqBackBy, MarketingNetNum, ConID, BankPay, InterFlag, pikadon, SInvPrintStyle, ExtraText1, ExtraText2, ExtraText3, ExtraText4, ExtraText5, ExtraSum1, ExtraSum2, ExtraSum3, CRMAcc, Contact, KupaNum, PointsBalance, RntFlag, Ddeposit, Ddsum, PayTotal, Miv, DEF_DUEDATE, DFT_ZELEM, DEF_ITEM_W, DEF_DATE3, DFT_ZELEM_ITEM, LastStatus, KUTime, KuChange, KuDate, KuZNum, DistLine, FMimshak, KupaNumFix, ExFile, KupaNumBaUp, DDComm, RndSuf, BaseOrderStockId, ContactMail, MimshStatus, Osek874, RefNum, BurdType, CurrStat, CloseType, CloseSum, ShopFlags, VatFree, KbMatchFlag, ExtraNum1, ExtraNum2, ExtraDate1, ExtraDate2, RefNumFlag, OpenBaseBase, VatFactor, CloseTypeKab, ConLogID, DocCancel, StationID, CloseTypeKabala, CustomerOrderNo, DocCancelUsefID, DocCancelDate, DocCancelTime, ExtraRemarks, TftalDlr, TftalVatDlr, TftalVatFreeDlr, MasavConfirm, PrintTypeMailSend, MasofCreateDate, MasofLogFrom, TaxApiNumber, AdtSum1, AdtSum2, AdtSum3, AdtText1, AdtText2, AdtText3, AdtNum1, AdtNum2, AdtNum3, AdtDate1, AdtDate2, AdtDate3, ConIssueNum, TaxApiNumberFlag, TaxApiNumberNum, TaxApiErrorText, TaxApiExtraText, BaseCancelDocID, PaymentMethodCode, RoundingMeth, ReceiptDonation, TaxEmergencyNumUsed, BankCode, BranchCode, BankAccount, MarketingNet
) SELECT
  DocumentID, DocNumber, Status, AccountKey, AccountName, Address, City, Phone, Batch, TerminalDoc, ValueDate, DueDate, PayDate, Copies, TransType, VatFreeTransType, DiscountPrc, TFtal, VatPrc, TFtalVatFree, TFtalVat, Reference, N'טסט קלון - למחיקה', PrintStyle, OriginalPrinted, Details, StockBatch, Warehouse, Agent, TaxType, EvalCurrency, Currency, FatherPriceList, SonPriceList, TransStore, TransAgent, ProtocolID, ExportAddr, UseFID, BranchID, Rate, MainRate, DiscountPrcR, IssueDate, Quantity, Ref3, CostCode, CheqAccKey, CheqBackBy, MarketingNetNum, ConID, BankPay, InterFlag, pikadon, SInvPrintStyle, ExtraText1, ExtraText2, ExtraText3, ExtraText4, ExtraText5, ExtraSum1, ExtraSum2, ExtraSum3, CRMAcc, Contact, KupaNum, PointsBalance, RntFlag, Ddeposit, Ddsum, PayTotal, Miv, DEF_DUEDATE, DFT_ZELEM, DEF_ITEM_W, DEF_DATE3, DFT_ZELEM_ITEM, LastStatus, KUTime, KuChange, KuDate, KuZNum, DistLine, FMimshak, KupaNumFix, ExFile, KupaNumBaUp, DDComm, RndSuf, BaseOrderStockId, ContactMail, MimshStatus, Osek874, RefNum, BurdType, CurrStat, CloseType, CloseSum, ShopFlags, VatFree, KbMatchFlag, ExtraNum1, ExtraNum2, ExtraDate1, ExtraDate2, RefNumFlag, OpenBaseBase, VatFactor, CloseTypeKab, ConLogID, DocCancel, StationID, CloseTypeKabala, CustomerOrderNo, DocCancelUsefID, DocCancelDate, DocCancelTime, ExtraRemarks, TftalDlr, TftalVatDlr, TftalVatFreeDlr, MasavConfirm, PrintTypeMailSend, MasofCreateDate, MasofLogFrom, TaxApiNumber, AdtSum1, AdtSum2, AdtSum3, AdtText1, AdtText2, AdtText3, AdtNum1, AdtNum2, AdtNum3, AdtDate1, AdtDate2, AdtDate3, ConIssueNum, TaxApiNumberFlag, TaxApiNumberNum, TaxApiErrorText, TaxApiExtraText, BaseCancelDocID, PaymentMethodCode, RoundingMeth, ReceiptDonation, TaxEmergencyNumUsed, BankCode, BranchCode, BankAccount, MarketingNet
FROM Stock WHERE ID=116994;
DECLARE @sid int = SCOPE_IDENTITY();
PRINT 'new clone Stock.ID=' + CAST(@sid AS varchar);
INSERT INTO StockMoves (
  StockID, ItemName, ItemKey, Warehouse, Agent, Reference, Details, DocumentID, DueDate, AlterNum, Unit, Status, CurrencyCode, Rate, Price, Quantity, TFtal, DiscountPrc, Tree, BaseMoveID, SupplyQuantity, BaseQuantity, BaseDate, SaleTaxPrc, CommisionPrc, BaseFlag, VatExampt, TreeFatherMoveID, Packs, SupplyPacks, CommisionPaid, Instance, BurdonOn, BurdInstance, CancelDate, PurchQuantity, JurnalAcc, BurdInstItemKey, ExpireDate, BranchID, ProductionID, InstanceFrom, BatchNum, Localization, WarrentyDate, FMPay, SourceMoveID, VatPrc, TVat, PayAcc, MIVID, AssKey, OriginalQnt, OriginalBaseQnt, OPrice, OPriceCurrencyCode, KupGift, TftalVat, LineNum, BaseLineNum, ExtraText1, ExtraText2, ExtraSum1, ExtraSum2, VatPrice, CounterVal, BaseDocType, LineNoForSorting, ODiscountPrc, CountQuant, BurdLineClose, ExFile, CancelBalUsef, CancelBalQuant, StockValPrice, PurchPrice, PurchPriceCurr, GPFlag, RePriced, ORate, ShopFlags, CostCode, JurnalAccSource, AlterName, TreeVer, ExtraNum1, ExtraNum2, ExtraDate1, ExtraDate2, PurchPriceRate, MoveCancel, CustomerOrderNo, CloseLineType, TftalDlr, BaseMoveIdBCancel, AdtSum1, AdtSum2, AdtSum3, AdtText1, AdtText2, AdtText3, AdtNum1, AdtNum2, AdtNum3, AdtDate1, AdtDate2, AdtDate3, EduCodeNum, EduCodeName, IDBeforeChange, TaxItemsCode, QuantToCancel
) SELECT
  @sid, ItemName, ItemKey, Warehouse, Agent, Reference, Details, DocumentID, DueDate, AlterNum, Unit, Status, CurrencyCode, Rate, Price, Quantity, TFtal, DiscountPrc, Tree, BaseMoveID, SupplyQuantity, BaseQuantity, BaseDate, SaleTaxPrc, CommisionPrc, BaseFlag, VatExampt, TreeFatherMoveID, Packs, SupplyPacks, CommisionPaid, Instance, BurdonOn, BurdInstance, CancelDate, PurchQuantity, JurnalAcc, BurdInstItemKey, ExpireDate, BranchID, ProductionID, InstanceFrom, BatchNum, Localization, WarrentyDate, FMPay, SourceMoveID, VatPrc, TVat, PayAcc, MIVID, AssKey, OriginalQnt, OriginalBaseQnt, OPrice, OPriceCurrencyCode, KupGift, TftalVat, LineNum, BaseLineNum, ExtraText1, ExtraText2, ExtraSum1, ExtraSum2, VatPrice, CounterVal, BaseDocType, LineNoForSorting, ODiscountPrc, CountQuant, BurdLineClose, ExFile, CancelBalUsef, CancelBalQuant, StockValPrice, PurchPrice, PurchPriceCurr, GPFlag, RePriced, ORate, ShopFlags, CostCode, JurnalAccSource, AlterName, TreeVer, ExtraNum1, ExtraNum2, ExtraDate1, ExtraDate2, PurchPriceRate, MoveCancel, CustomerOrderNo, CloseLineType, TftalDlr, BaseMoveIdBCancel, AdtSum1, AdtSum2, AdtSum3, AdtText1, AdtText2, AdtText3, AdtNum1, AdtNum2, AdtNum3, AdtDate1, AdtDate2, AdtDate3, EduCodeNum, EduCodeName, IDBeforeChange, TaxItemsCode, QuantToCancel
FROM StockMoves WHERE StockID=116994;
SELECT 'HEADER' c, ID, DocumentID, DocNumber, Status, CloseType, AccountKey, TFtal FROM Stock WHERE ID=@sid;
SELECT 'LINES' c, StockID, DocumentID, ItemKey, ItemName, Quantity, Price, TFtal, Status, LineNum FROM StockMoves WHERE StockID=@sid;
ROLLBACK;
PRINT 'ROLLED BACK - dry run (change ROLLBACK->COMMIT to keep)';