SET NOCOUNT ON;
BEGIN TRAN;
DECLARE @num int = (SELECT ISNULL(MAX(DocNumber),0)+1 FROM Stock WHERE DocumentID=31);
PRINT 'using DocNumber=' + CAST(@num AS varchar);
INSERT INTO Stock (
  DocumentID, DocNumber, Status, AccountKey, AccountName, Address, City, Phone, Batch, TerminalDoc, ValueDate, DueDate, PayDate, Copies, TransType, VatFreeTransType, DiscountPrc, TFtal, VatPrc, TFtalVatFree, TFtalVat, Reference, Remarks, PrintStyle, OriginalPrinted, Details, StockBatch, Warehouse, Agent, TaxType, EvalCurrency, Currency, FatherPriceList, SonPriceList, TransStore, TransAgent, ProtocolID, ExportAddr, UseFID, BranchID, Rate, MainRate, DiscountPrcR, IssueDate, Quantity, Ref3, CostCode, CheqAccKey, CheqBackBy, MarketingNetNum, ConID, BankPay, InterFlag, pikadon, SInvPrintStyle, ExtraText1, ExtraText2, ExtraText3, ExtraText4, ExtraText5, ExtraSum1, ExtraSum2, ExtraSum3, CRMAcc, Contact, KupaNum, PointsBalance, RntFlag, Ddeposit, Ddsum, PayTotal, Miv, DEF_DUEDATE, DFT_ZELEM, DEF_ITEM_W, DEF_DATE3, DFT_ZELEM_ITEM, LastStatus, KUTime, KuChange, KuDate, KuZNum, DistLine, FMimshak, KupaNumFix, ExFile, KupaNumBaUp, DDComm, RndSuf, BaseOrderStockId, ContactMail, MimshStatus, Osek874, RefNum, BurdType, CurrStat, CloseType, CloseSum, ShopFlags, VatFree, KbMatchFlag, ExtraNum1, ExtraNum2, ExtraDate1, ExtraDate2, RefNumFlag, OpenBaseBase, VatFactor, CloseTypeKab, ConLogID, DocCancel, StationID, CloseTypeKabala, CustomerOrderNo, DocCancelUsefID, DocCancelDate, DocCancelTime, ExtraRemarks, TftalDlr, TftalVatDlr, TftalVatFreeDlr, MasavConfirm, PrintTypeMailSend, MasofCreateDate, MasofLogFrom, TaxApiNumber, AdtSum1, AdtSum2, AdtSum3, AdtText1, AdtText2, AdtText3, AdtNum1, AdtNum2, AdtNum3, AdtDate1, AdtDate2, AdtDate3, ConIssueNum, TaxApiNumberFlag, TaxApiNumberNum, TaxApiErrorText, TaxApiExtraText, BaseCancelDocID, PaymentMethodCode, RoundingMeth, ReceiptDonation, TaxEmergencyNumUsed, BankCode, BranchCode, BankAccount, MarketingNet
) SELECT
  DocumentID, @num, Status, '10', N'לקוחות שונים לא לליקוט', '', '', '', Batch, TerminalDoc, CAST(GETDATE() AS date), CAST(GETDATE() AS date), CAST(GETDATE() AS date), Copies, TransType, VatFreeTransType, 0, 32.0, 0, 0, 0, NULL, N'טסט אוטומטי - למחיקה', PrintStyle, OriginalPrinted, Details, StockBatch, Warehouse, 0, TaxType, EvalCurrency, Currency, FatherPriceList, SonPriceList, TransStore, TransAgent, ProtocolID, ExportAddr, UseFID, BranchID, Rate, MainRate, DiscountPrcR, IssueDate, Quantity, Ref3, CostCode, CheqAccKey, CheqBackBy, MarketingNetNum, ConID, BankPay, InterFlag, pikadon, SInvPrintStyle, ExtraText1, ExtraText2, ExtraText3, ExtraText4, ExtraText5, ExtraSum1, ExtraSum2, ExtraSum3, CRMAcc, Contact, KupaNum, PointsBalance, RntFlag, Ddeposit, Ddsum, PayTotal, Miv, DEF_DUEDATE, DFT_ZELEM, DEF_ITEM_W, DEF_DATE3, DFT_ZELEM_ITEM, LastStatus, KUTime, KuChange, KuDate, KuZNum, DistLine, FMimshak, KupaNumFix, ExFile, KupaNumBaUp, DDComm, RndSuf, BaseOrderStockId, ContactMail, MimshStatus, Osek874, RefNum, BurdType, CurrStat, CloseType, CloseSum, ShopFlags, VatFree, KbMatchFlag, ExtraNum1, ExtraNum2, ExtraDate1, ExtraDate2, RefNumFlag, OpenBaseBase, VatFactor, CloseTypeKab, ConLogID, DocCancel, StationID, CloseTypeKabala, CustomerOrderNo, DocCancelUsefID, DocCancelDate, DocCancelTime, ExtraRemarks, TftalDlr, TftalVatDlr, TftalVatFreeDlr, MasavConfirm, PrintTypeMailSend, MasofCreateDate, MasofLogFrom, TaxApiNumber, AdtSum1, AdtSum2, AdtSum3, AdtText1, AdtText2, AdtText3, AdtNum1, AdtNum2, AdtNum3, AdtDate1, AdtDate2, AdtDate3, ConIssueNum, TaxApiNumberFlag, TaxApiNumberNum, TaxApiErrorText, TaxApiExtraText, BaseCancelDocID, PaymentMethodCode, RoundingMeth, ReceiptDonation, TaxEmergencyNumUsed, BankCode, BranchCode, BankAccount, MarketingNet
FROM Stock WHERE ID=116957;
DECLARE @sid int = SCOPE_IDENTITY();
PRINT 'new Stock.ID=' + CAST(@sid AS varchar);
INSERT INTO StockMoves (
  StockID, ItemName, ItemKey, Warehouse, Agent, Reference, Details, DocumentID, DueDate, AlterNum, Unit, Status, CurrencyCode, Rate, Price, Quantity, TFtal, DiscountPrc, Tree, BaseMoveID, SupplyQuantity, BaseQuantity, BaseDate, SaleTaxPrc, CommisionPrc, BaseFlag, VatExampt, TreeFatherMoveID, Packs, SupplyPacks, CommisionPaid, Instance, BurdonOn, BurdInstance, CancelDate, PurchQuantity, JurnalAcc, BurdInstItemKey, ExpireDate, BranchID, ProductionID, InstanceFrom, BatchNum, Localization, WarrentyDate, FMPay, SourceMoveID, VatPrc, TVat, PayAcc, MIVID, AssKey, OriginalQnt, OriginalBaseQnt, OPrice, OPriceCurrencyCode, KupGift, TftalVat, LineNum, BaseLineNum, ExtraText1, ExtraText2, ExtraSum1, ExtraSum2, VatPrice, CounterVal, BaseDocType, LineNoForSorting, ODiscountPrc, CountQuant, BurdLineClose, ExFile, CancelBalUsef, CancelBalQuant, StockValPrice, PurchPrice, PurchPriceCurr, GPFlag, RePriced, ORate, ShopFlags, CostCode, JurnalAccSource, AlterName, TreeVer, ExtraNum1, ExtraNum2, ExtraDate1, ExtraDate2, PurchPriceRate, MoveCancel, CustomerOrderNo, CloseLineType, TftalDlr, BaseMoveIdBCancel, AdtSum1, AdtSum2, AdtSum3, AdtText1, AdtText2, AdtText3, AdtNum1, AdtNum2, AdtNum3, AdtDate1, AdtDate2, AdtDate3, EduCodeNum, EduCodeName, IDBeforeChange, TaxItemsCode, QuantToCancel
) SELECT TOP 1
  @num, N'קפוצון קנגרו פוטר Keds 14', 'K610208_PINK', 1, 0, 0, Details, 1, DueDate, AlterNum, Unit, 1, N'ש"ח', 1.0, 32.0, 1, 32.0, 0, 0, 0, 1, 1, BaseDate, SaleTaxPrc, CommisionPrc, BaseFlag, VatExampt, 0, 0, 0, CommisionPaid, Instance, BurdonOn, BurdInstance, CancelDate, PurchQuantity, JurnalAcc, BurdInstItemKey, ExpireDate, BranchID, ProductionID, InstanceFrom, BatchNum, Localization, WarrentyDate, FMPay, SourceMoveID, 0, 0, PayAcc, MIVID, AssKey, 0, 0, 32.0, N'ש"ח', KupGift, 0, 1, 0, ExtraText1, ExtraText2, ExtraSum1, ExtraSum2, 0, CounterVal, 0, 1, 0, CountQuant, BurdLineClose, ExFile, CancelBalUsef, CancelBalQuant, 0, 0, PurchPriceCurr, GPFlag, RePriced, 1.0, ShopFlags, CostCode, JurnalAccSource, AlterName, TreeVer, ExtraNum1, ExtraNum2, ExtraDate1, ExtraDate2, PurchPriceRate, MoveCancel, CustomerOrderNo, CloseLineType, TftalDlr, BaseMoveIdBCancel, AdtSum1, AdtSum2, AdtSum3, AdtText1, AdtText2, AdtText3, AdtNum1, AdtNum2, AdtNum3, AdtDate1, AdtDate2, AdtDate3, EduCodeNum, EduCodeName, IDBeforeChange, TaxItemsCode, QuantToCancel
FROM StockMoves WHERE StockID=77058;
SELECT 'HEADER' AS chk, ID, DocumentID, DocNumber, Status, AccountKey, AccountName, TFtal FROM Stock WHERE ID=@sid;
SELECT 'LINES' AS chk, StockID, ItemKey, ItemName, Quantity, Price, TFtal, Status, LineNum FROM StockMoves WHERE StockID=@num;
ROLLBACK;
PRINT 'ROLLED BACK - dry run complete';